SELECT DEPARTAMENTO, MUNICIPIO, latitud,longitud
FROM PRO_TT_IPS I
INNER JOIN PRO_TT_DIVIPOLA D ON (UPPER(I.DEPARTAMENTO)||I.MUNICIPIO = D.NOM_DPTO||D.NOM_MPIO)
GROUP BY DEPARTAMENTO, MUNICIPIO, latitud,longitud;
--29894  Filas



SELECT DEPARTAMENTO FROM PRO_TT_IPS GROUP BY DEPARTAMENTO;
/*
Amazonas
Antioquia
Arauca
Atlántico
Barranquilla
Bogotá D.C  BOGOTÁ, D.C.
Bolívar
Boyacá
Buenaventura    VALLE DEL CAUCA
Caldas
Cali        VALLE DEL CAUCA
Caquetá
Cartagena   Bolívar
Casanare
Cauca
Cesar
Chocó
Córdoba
Cundinamarca
Guainía
Guaviare
Huila
La Guajira
Magdalena
Meta
Nariño
Norte de Santander
Putumayo
Quindío
Risaralda
San Andrés y Providencia
Santa Marta
Santander
Sucre
Tolima
Valle del cauca
Vaupés
Vichada

*/

UPDATE PRO_TT_IPS SET DEPARTAMENTO= 'Bogotá, D.C.' WHERE DEPARTAMENTO='Bogotá D.C';
UPDATE PRO_TT_IPS SET DEPARTAMENTO= 'Valle del Cauca' WHERE DEPARTAMENTO='Buenaventura';
UPDATE PRO_TT_IPS SET DEPARTAMENTO= 'Valle del Cauca' WHERE DEPARTAMENTO='Cali';
UPDATE PRO_TT_IPS SET DEPARTAMENTO= 'Bolívar' WHERE DEPARTAMENTO='Cartagena';
COMMIT;



SELECT MUNICIPIO FROM PRO_TT_IPS GROUP BY MUNICIPIO ORDER BY 1 ASC;
SELECT NOM_MPIO FROM PRO_TT_DIVIPOLA GROUP BY NOM_MPIO ORDER BY 1 ASC;

/*ACTUALIZACION DEL NOMBRE DEL MUNICIPÌO*/
UPDATE PRO_TT_IPS SET MUNICIPIO='ÁBREGO' WHERE MUNICIPIO='ABREGO';
UPDATE PRO_TT_IPS SET MUNICIPIO='ALTO BAUDÓ' WHERE MUNICIPIO='ALTO BAUDO';
UPDATE PRO_TT_IPS SET MUNICIPIO='ANCUYA' WHERE MUNICIPIO='ANCUYÁ';
UPDATE PRO_TT_IPS SET MUNICIPIO='ANZÁ' WHERE MUNICIPIO='ANZA';
UPDATE PRO_TT_IPS SET MUNICIPIO='BARRANCOMINAS' WHERE MUNICIPIO='BARRANCO MINAS';
UPDATE PRO_TT_IPS SET MUNICIPIO='BELÉN DE LOS ANDAQUÍES' WHERE MUNICIPIO='BELÉN DE LOS ANDAQUIES';
UPDATE PRO_TT_IPS SET MUNICIPIO='BOGOTÁ, D.C.' WHERE MUNICIPIO='BOGOTÁ';
UPDATE PRO_TT_IPS SET MUNICIPIO='BOJAYÁ' WHERE MUNICIPIO='BOJAYA';
UPDATE PRO_TT_IPS SET MUNICIPIO='CÁCHIRA' WHERE MUNICIPIO='CACHIRÁ';
UPDATE PRO_TT_IPS SET MUNICIPIO='CALARCÁ' WHERE MUNICIPIO='CALARCA';
UPDATE PRO_TT_IPS SET MUNICIPIO='CÁQUEZA' WHERE MUNICIPIO='CAQUEZA';
UPDATE PRO_TT_IPS SET MUNICIPIO='CARMEN DEL DARIÉN' WHERE MUNICIPIO='CARMEN DEL DARIEN';
UPDATE PRO_TT_IPS SET MUNICIPIO='CARTAGENA DE INDIAS' WHERE MUNICIPIO='CARTAGENA';
UPDATE PRO_TT_IPS SET MUNICIPIO='CARURÚ' WHERE MUNICIPIO='CARURU';
UPDATE PRO_TT_IPS SET MUNICIPIO='CERRO DE SAN ANTONIO' WHERE MUNICIPIO='CERRO SAN ANTONIO';
UPDATE PRO_TT_IPS SET MUNICIPIO='CHÁMEZA' WHERE MUNICIPIO='CHAMEZA';
UPDATE PRO_TT_IPS SET MUNICIPIO='' WHERE MUNICIPIO='CHIBOLO';
UPDATE PRO_TT_IPS SET MUNICIPIO='COLOSÓ' WHERE MUNICIPIO='COLOSO';
UPDATE PRO_TT_IPS SET MUNICIPIO='CONSACÁ' WHERE MUNICIPIO='CONSACA';
UPDATE PRO_TT_IPS SET MUNICIPIO='CUASPUD CARLOSAMA' WHERE MUNICIPIO='CUASPUD';
UPDATE PRO_TT_IPS SET MUNICIPIO='' WHERE MUNICIPIO='CÚCUTA';
UPDATE PRO_TT_IPS SET MUNICIPIO='DONMATÍAS' WHERE MUNICIPIO='DON MATÍAS';
UPDATE PRO_TT_IPS SET MUNICIPIO='EL PAUJÍL' WHERE MUNICIPIO='EL PAUJIL';
UPDATE PRO_TT_IPS SET MUNICIPIO='EL PIÑÓN' WHERE MUNICIPIO='EL PIÑON';
UPDATE PRO_TT_IPS SET MUNICIPIO='ENTRERRÍOS' WHERE MUNICIPIO='ENTRERRIOS';
UPDATE PRO_TT_IPS SET MUNICIPIO='FÓMEQUE' WHERE MUNICIPIO='FOMEQUE';
UPDATE PRO_TT_IPS SET MUNICIPIO='GACHALÁ' WHERE MUNICIPIO='GACHALA';
UPDATE PRO_TT_IPS SET MUNICIPIO='GÁMBITA' WHERE MUNICIPIO='GAMBITA';
UPDATE PRO_TT_IPS SET MUNICIPIO='GÁMEZA' WHERE MUNICIPIO='GAMEZA';
UPDATE PRO_TT_IPS SET MUNICIPIO='GUATAPÉ' WHERE MUNICIPIO='GUATAPE';
UPDATE PRO_TT_IPS SET MUNICIPIO='GUAYABAL DE SÍQUIMA' WHERE MUNICIPIO='GUAYABAL DE SIQUIMA';
UPDATE PRO_TT_IPS SET MUNICIPIO='GÜICÁN DE LA SIERRA' WHERE MUNICIPIO='GÜICÁN';
UPDATE PRO_TT_IPS SET MUNICIPIO='ÍQUIRA' WHERE MUNICIPIO='IQUIRA';
UPDATE PRO_TT_IPS SET MUNICIPIO='ITAGÜÍ' WHERE MUNICIPIO='ITAGUI';
UPDATE PRO_TT_IPS SET MUNICIPIO='LEBRIJA' WHERE MUNICIPIO='LEBRÍJA';
UPDATE PRO_TT_IPS SET MUNICIPIO='' WHERE MUNICIPIO=' LEGUÍZAMO';
UPDATE PRO_TT_IPS SET MUNICIPIO='LÓPEZ DE MICAY' WHERE MUNICIPIO='LÓPEZ';
UPDATE PRO_TT_IPS SET MUNICIPIO='MACHETÁ' WHERE MUNICIPIO='MACHETA';
UPDATE PRO_TT_IPS SET MUNICIPIO='MAGÜÍ' WHERE MUNICIPIO='MAGÜI';
UPDATE PRO_TT_IPS SET MUNICIPIO='' WHERE MUNICIPIO='MARIQUITA';
UPDATE PRO_TT_IPS SET MUNICIPIO='MIRITÍ - PARANÁ' WHERE MUNICIPIO='MIRITI - PARANÁ';
UPDATE PRO_TT_IPS SET MUNICIPIO='' WHERE MUNICIPIO=' MOMPÓS';
UPDATE PRO_TT_IPS SET MUNICIPIO='PÁEZ' WHERE MUNICIPIO='PAEZ';
UPDATE PRO_TT_IPS SET MUNICIPIO='' WHERE MUNICIPIO='PÁEZ';
UPDATE PRO_TT_IPS SET MUNICIPIO='PIENDAMÓ - TUNÍA' WHERE MUNICIPIO='PIENDAMÓ';
UPDATE PRO_TT_IPS SET MUNICIPIO='PURÍSIMA DE LA CONCEPCIÓN' WHERE MUNICIPIO='PURÍSIMA';
UPDATE PRO_TT_IPS SET MUNICIPIO='RÍO IRÓ' WHERE MUNICIPIO='RÍO IRO';
UPDATE PRO_TT_IPS SET MUNICIPIO='SABANAS DE SAN ÁNGEL' WHERE MUNICIPIO='SABANAS DE SAN ANGEL';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN ANDRÉS DE SOTAVENTO' WHERE MUNICIPIO='SAN ANDRÉS SOTAVENTO';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE URÉ' WHERE MUNICIPIO='SAN JOSE DE URÉ';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JUAN DE RIOSECO' WHERE MUNICIPIO='SAN JUAN DE RÍO SECO';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN PEDRO DE URABÁ' WHERE MUNICIPIO='SAN PEDRO DE URABA';
UPDATE PRO_TT_IPS SET MUNICIPIO='SONSÓN' WHERE MUNICIPIO='SONSON';
UPDATE PRO_TT_IPS SET MUNICIPIO='SOTARÁ PAISPAMBA' WHERE MUNICIPIO='SOTARA';
UPDATE PRO_TT_IPS SET MUNICIPIO='TORIBÍO' WHERE MUNICIPIO='TORIBIO';
UPDATE PRO_TT_IPS SET MUNICIPIO='TURBANÁ' WHERE MUNICIPIO='TURBANA';
UPDATE PRO_TT_IPS SET MUNICIPIO='ÚMBITA' WHERE MUNICIPIO='UMBITA';
COMMIT;



/*1. ACTUALIZACION DE NOMBRE DE DEPARTAMENTO - AGREGANDO TILDES*/
SELECT NOM_DPTO FROM PRO_TT_DIVIPOLA WHERE NOM_DPTO LIKE '%Á%' GROUP BY NOM_DPTO;

SELECT NOM_DPTO FROM PRO_TT_DIVIPOLA  GROUP BY NOM_DPTO;

SELECT * FROM PRO_TT_DIVIPOLA WHERE NOM_MPIO LIKE '%Á%';

SELECT * FROM PRO_TT_DIVIPOLA WHERE NOM_MPIO LIKE '%É%';

SELECT * FROM PRO_TT_DIVIPOLA WHERE NOM_MPIO LIKE '%Í%';

SELECT * FROM PRO_TT_DIVIPOLA WHERE NOM_MPIO LIKE '%Ó%';

SELECT * FROM PRO_TT_DIVIPOLA WHERE NOM_MPIO LIKE '%Ú%';



SELECT DEPARTAMENTO, MUNICIPIO, latitud,longitud
FROM PRO_TT_IPS I
INNER JOIN PRO_TT_DIVIPOLA D ON (UPPER(I.DEPARTAMENTO)||TRIM(I.MUNICIPIO) = D.NOM_DPTO||D.NOM_MPIO);

--29894  Filas

SELECT
COUNT(DEPARTAMENTO), --41427
COUNT( MUNICIPIO), --40780
COUNT( CODIGO_PRESTADOR), --41427
COUNT( NOMBRE_PRESTADOR), --41427
COUNT( NIT_IPS), --41427
COUNT( NUM_DIGITO_VERIFICION), --41399
COUNT( NATURALEZA), --41427
COUNT( NUM_NIVEL_ATENCION), --16161
COUNT( CODIGO_SEDE), --41427
COUNT( NUMERO_SEDE), --41427
COUNT( NOM_SEDE_IPS), --41427
COUNT( GERENTE), --41202
COUNT( DIRECCION), --41367
COUNT( EMAIL), --41362
COUNT( TELEFONO), --40118
COUNT( NOM_GRUPO_CAPACIDAD), --41427
COUNT( NOM_DESCRIPCION_CAPACIDAD), --41427
COUNT( NUM_CANTIDAD_CAPACIDAD_INSTALADA), --41427
COUNT( FECHA_CORTE), --41427
COUNT( FUENTE) --41427
FROM PRO_TT_IPS;



SELECT /*COUNT( *) ,MUNICIPIO*/ * FROM PRO_TT_IPS WHERE MUNICIPIO IS NULL;-- GROUP BY MUNICIPIO;

/*ACTUALIZACION DE DATOS MUNICIPIO REVISION DE LOS MUNICIPIOS NULOS
SE REALIZA LA EXTRACCION DE LOS PEIMEROS 5 DIGITOS DEL CODIGO DEL PRESTADOR QUE CONTIENE EL CONCATENADOS
LOS CODIGOS DE DEPARTAMENTO Y MUNICIPIO*/

SELECT DEPARTAMENTO, SUBSTR(CODIGO_PRESTADOR,1,5),CODIGO_PRESTADOR
FROM PRO_TT_IPS 
WHERE MUNICIPIO IS NULL 
GROUP BY DEPARTAMENTO, SUBSTR(CODIGO_PRESTADOR,1,5), CODIGO_PRESTADOR;


SELECT * FROM PRO_TT_DIVIPOLA
WHERE COD_DPTO='73';-- AND COD_MPIO='514';


/*ACTUALIZACION DE DATOS*/
UPDATE PRO_TT_IPS SET MUNICIPIO='PÁEZ' WHERE DEPARTAMENTO='Boyacá' AND CODIGO_PRESTADOR='1551400659';
UPDATE PRO_TT_IPS SET MUNICIPIO='POPAYÁN' WHERE DEPARTAMENTO='Cauca' AND CODIGO_PRESTADOR='1900109129';
UPDATE PRO_TT_IPS SET MUNICIPIO='PÁEZ' WHERE DEPARTAMENTO='Cauca' AND CODIGO_PRESTADOR='1951700071';
UPDATE PRO_TT_IPS SET MUNICIPIO='PÁEZ' WHERE DEPARTAMENTO='Cauca' AND CODIGO_PRESTADOR='1951700075';
UPDATE PRO_TT_IPS SET MUNICIPIO='PÁEZ' WHERE DEPARTAMENTO='Cauca' AND CODIGO_PRESTADOR='1951709388';
UPDATE PRO_TT_IPS SET MUNICIPIO='CHIVOLO' WHERE DEPARTAMENTO='Magdalena' AND CODIGO_PRESTADOR='4717000052';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100011';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100012';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100039';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100045';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100050';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100099';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100173';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100191';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100252';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100269';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100306';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100364';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100371';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100417';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100427';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100449';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100470';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100488';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100557';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100570';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100595';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100603';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100633';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100741';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100782';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100810';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100828';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100855';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100861';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400100967';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101007';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101144';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101172';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101273';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101394';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101413';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101459';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101480';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101485';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101509';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101517';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101532';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101533';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101563';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101564';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101569';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101606';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101610';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101615';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101659';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101661';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101663';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101700';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101705';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101733';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101738';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101749';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101756';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101759';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101766';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101780';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101791';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101801';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101817';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101818';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101840';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101862';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101868';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101872';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101880';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101882';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101913';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101915';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101916';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101918';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101941';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101947';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101948';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400101949';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102004';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102005';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102010';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102013';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102065';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102066';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102079';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102088';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102112';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102113';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102115';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102127';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102129';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102138';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102145';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102162';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102173';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102174';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102189';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102193';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102196';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102197';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102217';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102251';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102263';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102267';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102269';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102272';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102282';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102285';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102294';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102300';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102310';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102336';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102349';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102350';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102368';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102371';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102375';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102387';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102390';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102405';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102416';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102418';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102442';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102449';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102454';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102502';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102523';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102525';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102538';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102539';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102595';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102607';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102649';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102659';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102660';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102685';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102703';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102725';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102726';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102782';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102790';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102802';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102830';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102843';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102844';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102854';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102881';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102882';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102896';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102897';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102910';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102911';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102963';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102968';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102971';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400102986';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400103001';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400103002';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400103021';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400103034';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400103038';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400103043';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400103089';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400103102';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400103114';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400103136';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400103147';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400103153';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400103175';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400103188';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN JOSÉ DE CÚCUTA' WHERE DEPARTAMENTO='Norte de Santander' AND CODIGO_PRESTADOR='5400103245';
UPDATE PRO_TT_IPS SET MUNICIPIO='IBAGUÉ' WHERE DEPARTAMENTO='Tolima' AND CODIGO_PRESTADOR='7300100706';
UPDATE PRO_TT_IPS SET MUNICIPIO='IBAGUÉ' WHERE DEPARTAMENTO='Tolima' AND CODIGO_PRESTADOR='7300102875';
UPDATE PRO_TT_IPS SET MUNICIPIO='HONDA' WHERE DEPARTAMENTO='Tolima' AND CODIGO_PRESTADOR='7334902876';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN SEBASTIÁN DE MARIQUITA' WHERE DEPARTAMENTO='Tolima' AND CODIGO_PRESTADOR='7344301021';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN SEBASTIÁN DE MARIQUITA' WHERE DEPARTAMENTO='Tolima' AND CODIGO_PRESTADOR='7344301840';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN SEBASTIÁN DE MARIQUITA' WHERE DEPARTAMENTO='Tolima' AND CODIGO_PRESTADOR='7344302695';
UPDATE PRO_TT_IPS SET MUNICIPIO='SAN SEBASTIÁN DE MARIQUITA' WHERE DEPARTAMENTO='Tolima' AND CODIGO_PRESTADOR='7344302956';
COMMIT;

/********************************************************************************/
SELECT COUNT( *), NUM_DIGITO_VERIFICION FROM PRO_TT_IPS  GROUP BY NUM_DIGITO_VERIFICION;  --WHERE MUNICIPIO IS NULL;--

/*SE HACE LA HOMOLOGACION DE LOS NULOS A 0*/
UPDATE PRO_TT_IPS SET NUM_DIGITO_VERIFICION='0' WHERE NUM_DIGITO_VERIFICION IS NULL;
--28 filas actualizadas.
COMMIT;

/******************************************************************************/
SELECT COUNT( *), NUM_NIVEL_ATENCION FROM PRO_TT_IPS  GROUP BY NUM_NIVEL_ATENCION;

SELECT COUNT( *), NUM_NIVEL_ATENCION,CODIGO_PRESTADOR, NOMBRE_PRESTADOR
FROM PRO_TT_IPS 
WHERE NUM_NIVEL_ATENCION IS NULL 
GROUP BY NUM_NIVEL_ATENCION, CODIGO_PRESTADOR, NOMBRE_PRESTADOR ;

UPDATE PRO_TT_IPS SET NUM_NIVEL_ATENCION='SIN NIVEL' WHERE NUM_NIVEL_ATENCION IS NULL ;
COMMIT;

--25.266 filas actualizadas.


/********************************************************************************/
SELECT COUNT(*), GERENTE
FROM PRO_TT_IPS 
WHERE GERENTE IS NULL 
GROUP BY GERENTE;


UPDATE PRO_TT_IPS SET GERENTE='SIN GERENTE' WHERE GERENTE IS NULL ;
COMMIT;

--225 filas actualizadas


/********************************************************************************/
SELECT COUNT(*), DIRECCION
FROM PRO_TT_IPS 
WHERE DIRECCION IS NULL 
GROUP BY DIRECCION;

UPDATE PRO_TT_IPS SET DIRECCION='SIN DIRECCION' WHERE DIRECCION IS NULL ;
COMMIT;
--60 filas actualizadas.


/********************************************************************************/
SELECT COUNT(*), EMAIL
FROM PRO_TT_IPS 
WHERE EMAIL IS NULL 
GROUP BY EMAIL;

UPDATE PRO_TT_IPS SET EMAIL='SIN EMAIL' WHERE EMAIL IS NULL ;
COMMIT;

--65 filas actualizadas.


/********************************************************************************/
SELECT COUNT(*), TELEFONO
FROM PRO_TT_IPS 
WHERE TELEFONO IS NULL 
GROUP BY TELEFONO;

UPDATE PRO_TT_IPS SET TELEFONO='SIN TELEFONO' WHERE TELEFONO IS NULL ;
COMMIT;